DOMAIN = "nerdaxe_ultra"

ATTR_TEMP = "temp"
ATTR_POWER = "power"
ATTR_CURRENT = "current"
ATTR_CURRENT_A = "currentA"
ATTR_HASH_RATE = "hashRate"
ATTR_HASH_RATE_1M = "hashRate_1m"
ATTR_HASH_RATE_10M = "hashRate_10m"
ATTR_HASH_RATE_1H = "hashRate_1h"
ATTR_HASH_RATE_1D = "hashRate_1d"
ATTR_CORE_VOLTAGE = "coreVoltageActual"
ATTR_FAN_SPEED = "fanspeed"
ATTR_SHARES_ACCEPTED = "sharesAccepted"
ATTR_SHARES_REJECTED = "sharesRejected"